language: python

python:
    - 2.6
    - 2.7
    - pypy

matrix:
    allow_failures:
        - python: 2.6

install:
    - pip install -r requirements.txt
    - pip install coveralls

before_script:
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python --version; fi

script:
    - make lint
    - coverage run `which trial` silverberg

after_success:
    - coveralls
