language: python

python:
    - 2.6
    - 2.7
    - pypy

matrix:
    allow_failures:
        - python: 2.6

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then strace -q coverage run `which trial` silverberg 2>&1; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coverage run `which trial` silverberg; fi

after_success:
    - coveralls
