language: python

python:
    - 2.6
    - 2.7
    - pypy

matrix:
    allow_failures:
        - python: 2.6

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get -y update; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get install -y pypy; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo rm -rf /usr/local/pypy/bin; fi

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - make lint
    - coverage run `which trial` silverberg

after_success:
    - coveralls
