language: python

python:
    - 2.6
    - 2.7
    - pypy

matrix:
    allow_failures:
        - python: 2.6
        - python: pypy

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - make lint
    - coverage run `which trial` silverberg

after_success:
    - coveralls
